sphinx>=1.8.3     
docutils>=0.16.0

# Themes and visual 
# sphinx_rtd_theme   
readthedocs-sphinx-ext   
sphinx-material

# Tab UI elements
sphinx-tabs   

# visual diagrams etc 
sphinxcontrib-actdiag   
sphinxcontrib-blockdiag   
sphinxcontrib-contentui   
sphinxcontrib-seqdiag   
sphinxcontrib-nwdiag   
sphinxcontrib-plantuml   
sphinx-prompt   

# Remote files but Include like a normal literalinclude
sphinxext-remoteliteralinclude

# usage
# .. rli:: https://example.com/example.java
#    :language: java
#    :lines: 10-29
#    :linenos:
#    :lineno-start: 10


# Music notation that makes sound
#sphinxnotes-lilypond   

#sphinx-Timeline   

# helpful things
sphinx-copybutton   
sphinx-Hoverxref   
sphinx_issues   

# images
sphinx-gallery   
sphinxcontrib-images   

# git 
sphinx-gitstamp   

# page not found
sphinx-notfound-page   

# Redirects
#sphinx-Redirects   
#sphinxext.rediraffe   

# sitemap 
sphinx-Sitemap   

# templates
sphinx-Jinja   

# Twitter
#python-twitter   