American Institute for Economic Research
The 2006 Origins of the Lockdown Idea

Jeffrey A. Tucker 
– May 15, 2020

https://www.aier.org/article/the-2006-origins-of-the-lockdown-idea/

Reading Time: 9 minutes
AIER >> Daily Economy >> History >> Crisis

Now begins the grand effort, on display in thousands of articles and news broadcasts daily, somehow to normalize the lockdown and all its destruction of the last two months. We didn’t lock down almost the entire country in 1968/69, 1957, or 1949-1952, or even during 1918. But in a terrifying few days in March 2020, it happened to all of us, causing an avalanche of social, cultural, and economic destruction that will ring through the ages. 


There was nothing normal about it all. We’ll be trying to figure out what happened to us for decades hence. 


How did a temporary plan to preserve hospital capacity turn into two-to-three months of near-universal house arrest that ended up causing worker furloughs at 256 hospitals, a stoppage of international travel, a 40% job loss among people earning less than $40K per year, devastation of every economic sector, mass confusion and demoralization, a complete ignoring of all fundamental rights and liberties, not to mention the mass confiscation of private property with forced closures of millions of businesses?  


Whatever the answer, it’s got to be a bizarre tale. What’s truly surprising is just how recent the theory behind lockdown and forced distancing actually is. So far as anyone can tell, the intellectual machinery that made this mess was invented 14 years ago, and not by epidemiologists but by computer-simulation modelers. It was adopted not by experienced doctors – they warned ferociously against it – but by politicians. 


Let’s start with the phrase social distancing, which has mutated into forced human separation. The first I had heard it was in the 2011 movie Contagion. The first time it appeared in the New York Times was February 12, 2006:


If the avian flu goes pandemic while Tamiflu and vaccines are still in short supply, experts say, the only protection most Americans will have is “social distancing,” which is the new politically correct way of saying “quarantine.”


But distancing also encompasses less drastic measures, like wearing face masks, staying out of elevators — and the [elbow] bump. Such stratagems, those experts say, will rewrite the ways we interact, at least during the weeks when the waves of influenza are washing over us.


Maybe you don’t remember that the avian flu of 2006 didn’t amount to much. It’s true, despite all the extreme warnings about its lethality, H5N1 didn’t turn into much at all. What it did do, however, was send the existing president, George W. Bush, to the library to read about the 1918 flu and its catastrophic results. He asked for some experts to submit some plans to him about what to do when the real thing comes along. 


The New York Times (April 22, 2020) tells the story from there: 


Fourteen years ago, two federal government doctors, Richard Hatchett and Carter Mecher, met with a colleague at a burger joint in suburban Washington for a final review of a proposal they knew would be treated like a piñata: telling Americans to stay home from work and school the next time the country was hit by a deadly pandemic.


When they presented their plan not long after, it was met with skepticism and a degree of ridicule by senior officials, who like others in the United States had grown accustomed to relying on the pharmaceutical industry, with its ever-growing array of new treatments, to confront evolving health challenges.


Drs. Hatchett and Mecher were proposing instead that Americans in some places might have to turn back to an approach, self-isolation, first widely employed in the Middle Ages.


How that idea — born out of a request by President George W. Bush to ensure the nation was better prepared for the next contagious disease outbreak — became the heart of the national playbook for responding to a pandemic is one of the untold stories of the coronavirus crisis.


It required the key proponents — Dr. Mecher, a Department of Veterans Affairs physician, and Dr. Hatchett, an oncologist turned White House adviser — to overcome intense initial opposition.


It brought their work together with that of a Defense Department team assigned to a similar task.


And it had some unexpected detours, including a deep dive into the history of the 1918 Spanish flu and an important discovery kicked off by a high school research project pursued by the daughter of a scientist at the Sandia National Laboratories.


The concept of social distancing is now intimately familiar to almost everyone. But as it first made its way through the federal bureaucracy in 2006 and 2007, it was viewed as impractical, unnecessary and politically infeasible.


Notice that in the course of this planning, neither legal nor economic experts were brought in to consult and advise. Instead it fell to Mecher (formerly of Chicago and an intensive care doctor with no previous expertise in pandemics) and the oncologist Hatchett. 

High School Student
-----------------------

But what is this mention of the high-school daughter of 14? Her name is Laura M. Glass, and she recently declined to be interviewed when the Albuquerque Journal did a deep dive of this history. 


Laura, with some guidance from her dad, devised a computer simulation that showed how people – family members, co-workers, students in schools, people in social situations – interact. What she discovered was that school kids come in contact with about 140 people a day, more than any other group. Based on that finding, her program showed that in a hypothetical town of 10,000 people, 5,000 would be infected during a pandemic if no measures were taken, but only 500 would be infected if the schools were closed.


Laura’s name appears on the foundational paper arguing for lockdowns and forced human separation. That paper is Targeted Social Distancing Designs for Pandemic Influenza (2006). It set out a model for forced separation and applied it with good results backwards in time to 1957. They conclude with a chilling call for what amounts to a totalitarian lockdown, all stated very matter-of-factly. 


Implementation of social distancing strategies is challenging. They likely must be imposed for the duration of the local epidemic and possibly until a strain-specific vaccine is developed and distributed. If compliance with the strategy is high over this period, an epidemic within a community can be averted. However, if neighboring communities do not also use these interventions, infected neighbors will continue to introduce influenza and prolong the local epidemic, albeit at a depressed level more easily accommodated by healthcare systems.


In other words, it was a high-school science experiment that eventually became law of the land, and through a circuitous route propelled not by science but politics. 


The primary author of this paper was Robert J. Glass, a complex-systems analyst with Sandia National Laboratories. He had no medical training, much less an expertise in immunology or epidemiology. 


That explains why Dr. D.A. Henderson, “who had been the leader of the international effort to eradicate smallpox,” completely rejected the whole scheme. 


Says the NYT:


Dr. Henderson was convinced that it made no sense to force schools to close or public gatherings to stop. Teenagers would escape their homes to hang out at the mall. School lunch programs would close, and impoverished children would not have enough to eat. Hospital staffs would have a hard time going to work if their children were at home.


The measures embraced by Drs. Mecher and Hatchett would “result in significant disruption of the social functioning of communities and result in possibly serious economic problems,” Dr. Henderson wrote in his own academic paper responding to their ideas.


The answer, he insisted, was to tough it out: Let the pandemic spread, treat people who get sick and work quickly to develop a vaccine to prevent it from coming back.


AIER’s Phil Magness got to work to find the literature responding to the 2006 paper by Robert and Laura M. Glass and discovered the following manifesto: Disease Mitigation Measures in the Control of Pandemic Influenza. The authors included D.A. Henderson, along with three professors from Johns Hopkins: infectious disease specialist Thomas V.Inglesby, epidemiologist Jennifer B. Nuzzo, and physician Tara O’Toole. 


Paper is a remarkable refutation of lockdowns
------------------------------------------------

Their paper is a remarkably readable refutation of the entire lockdown model. 


There are no historical observations or scientific studies that support the confinement by quarantine of groups of possibly infected people for extended periods in order to slow the spread of influenza. … It is difficult to identify circumstances in the past half-century when large-scale quarantine has been effectively used in the control of any disease. The negative consequences of large-scale quarantine are so extreme (forced confinement of sick people with the well; complete restriction of movement of large populations; difficulty in getting critical supplies, medicines, and food to people inside the quarantine zone) that this mitigation measure should be eliminated from serious consideration…


Home quarantine also raises ethical questions. Implementation of home quarantine could result in healthy, uninfected people being placed at risk of infection from sick household members. Practices to reduce the chance of transmission (hand-washing, maintaining a distance of 3 feet from infected people, etc.) could be recommended, but a policy imposing home quarantine would preclude, for example, sending healthy children to stay with relatives when a family member becomes ill. Such a policy would also be particularly hard on and dangerous to people living in close quarters, where the risk of infection would be heightened…. 


Travel restrictions, such as closing airports and screening travelers at borders, have historically been ineffective. The World Health Organization Writing Group concluded that “screening and quarantining entering travelers at international borders did not substantially delay virus introduction in past pandemics . . . and will likely be even less effective in the modern era.”… It is reasonable to assume that the economic costs of shutting down air or train travel would be very high, and the societal costs involved in interrupting all air or train travel would be extreme. …


During seasonal influenza epidemics, public events with an expected large attendance have sometimes been cancelled or postponed, the rationale being to decrease the number of contacts with those who might be contagious. There are, however, no certain indications that these actions have had any definitive effect on the severity or duration of an epidemic. Were consideration to be given to doing this on a more extensive scale and for an extended period, questions immediately arise as to how many such events would be affected. There are many social gatherings that involve close contacts among people, and this prohibition might include church services, athletic events, perhaps all meetings of more than 100 people. It might mean closing theaters, restaurants, malls, large stores, and bars. Implementing such measures would have seriously disruptive consequences…


Schools are often closed for 1–2 weeks early in the development of seasonal community outbreaks of influenza primarily because of high absentee rates, especially in elementary schools, and because of illness among teachers. This would seem reasonable on practical grounds. However, to close schools for longer periods is not only impracticable but carries the possibility of a serious adverse outcome….


Thus, cancelling or postponing large meetings would not be likely to have any significant effect on the development of the epidemic. While local concerns may result in the closure of particular events for logical reasons, a policy directing communitywide closure of public events seems inadvisable. Quarantine. As experience shows, there is no basis for recommending quarantine either of groups or individuals. The problems in implementing such measures are formidable, and secondary effects of absenteeism and community disruption as well as possible adverse consequences, such as loss of public trust in government and stigmatization of quarantined people and groups, are likely to be considerable….

Remarkable Conclusion
----------------------------------------

Finally, the remarkable conclusion:

Experience has shown that communities faced with epidemics or other adverse events respond best and with the least anxiety when the normal social functioning of the community is least disrupted. Strong political and public health leadership to provide reassurance and to ensure that needed medical care services are provided are critical elements. If either is seen to be less than optimal, a manageable epidemic could move toward catastrophe.


Confronting a manageable epidemic and turning it into a catastrophe: that seems like a good description of everything that has happened in the COVID-19 crisis of 2020. 


Thus did some of the most highly trained and experienced experts on epidemics warn with biting rhetoric against everything that the advocates of lockdown proposed. It was not even a real-world idea in the first place and showed no actual knowledge of viruses and disease mitigation. Again, the idea was born of a high-school science experiment using agent-based modelling techniques having nothing at all to do with real life, real science, or real medicine. 


So the question becomes: how did the extreme view prevail?


The New York Times has the answer:


The [Bush] administration ultimately sided with the proponents of social distancing and shutdowns — though their victory was little noticed outside of public health circles. Their policy would become the basis for government planning and would be used extensively in simulations used to prepare for pandemics, and in a limited way in 2009 during an outbreak of the influenza called H1N1. Then the coronavirus came, and the plan was put to work across the country for the first time.


[Post-publication note: You can read the 2007 CDC paper here. It is arguable that this paper did not favor full lockdown. I’ve spoken to Rajeev Venkayya, MD, who regards the 2007 plan as more liberal, and assures me that they never envisioned this level of lockdown: “lockdowns and shelter-in-place were not part of the recommendations.” To my mind, fleshing out the full relationship between this 2007 document and current policy requires a separate article.]


The Times called one of the pro-lockdown researchers, Dr. Howard Markel, and asked what he thought of the lockdowns. His answer: he is glad that his work was used to “save lives” but added, “It is also horrifying.” “We always knew this would be applied in worst-case scenarios,” he said. “Even when you are working on dystopian concepts, you always hope it will never be used.”


Ideas have consequences, as they say. Dream up an idea for a virus-controlling totalitarian society, one without an endgame and eschewing any experienced-based evidence that it would achieve the goal, and you might see it implemented someday. Lockdown might be the new orthodoxy but that doesn’t make it medically sound or morally correct. At least now we know that many great doctors and scholars in 2006 did their best to stop this nightmare from unfolding. Their mighty paper should serve as a blueprint for dealing with the next pandemic. 


Correction: A previous version of this article in one instance incorrectly named the coauthor of the 2006 paper by Robert Glass. That is now corrected to Laura M. Glass.


Jeffrey A. Tucker


Jeffrey A. Tucker is Editorial Director for the American Institute for Economic Research.


He is the author of many thousands of articles in the scholarly and popular press and nine books in 5 languages, most recently Liberty or Lockdown. He is also the editor of The Best of Mises. He speaks widely on topics of economics, technology, social philosophy, and culture.


Jeffrey is available for speaking and interviews via his email.  Tw | FB | LinkedIn




